'Algoritmo "é real agr"
// 
//  
// Descrição   : Escolha oficial do seu futuro (função)
// Autor(a)    : De Aline Cecilia para Maria Leticia
// Data atual  : 01/04/2023
Var
// Seção de Declarações das variáveis
comecar: CARACTER
decisao: INTEIRO


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Boa Noite, Maria")
escreval ()
escreval ("Você esta pronta para começar?")
leia (comecar)

Fimalgoritmo